### ISSUE TITLE
Consider renaming the class to ModuleMigrateController

### ISSUE THREAD

**Issue by cebe** [bariew/yii2-module-migration-controller#6]
It extends `MigrateController` and adds module feature so a more suitable class name would be `ModuleMigrateController`.
Should be done in a major version though because it breaks backwards compatibility...

**Comment by bariew** [comment]
Yes, thank you very much, I merged all your requests and added controller with correct name (leaved old one too yet).

**Comment by cebe** [comment]
Awesome :) Can you adjust the README about the name too?
